version: "3.9"

services:
  nginx-php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: template_nginx-php
    hostname: nginx-php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/www
      - ./log/nginx:/var/log/nginx/
      - ./log/php:/var/log/php8/
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/http.d/default.conf:/etc/nginx/http.d/default.conf
      - ./config/php/php.ini:/etc/php8/php.ini
      - ./config/php/php-fpm.conf:/etc/php8/php-fpm.conf
      - ./config/php/php-fpm.d/www.conf:/etc/php8/php-fpm.d/www.conf
      - ./config/php/conf.d/00_xdebug.ini:/etc/php8/conf.d/00_xdebug.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
